import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import "./globals.css";
import {Sidebar} from "@/components/Sidebar";


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className={poppins.className + " h-full antialiased"}
    >
      <body className="flex min-h-screen">
        <Sidebar/>
        {children}
        </body>
    </html>
  );
}
